<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.seetest.apps.supervalu.tests.Sanity" tests="2" time="147.902" ignored="0" failures="0" timestamp="13 יונ 2017 20:10:55 GMT" skipped="0" hostname="AmitNahum" errors="1">
  <testcase name="VerfiyHomePageUI" time="67.265" classname="com.seetest.apps.supervalu.tests.Sanity">
    <error type="com.experitest.client.InternalException" message="Exception caught while executing click: Element was not identified: &#039;//*[@id=&#039;my_account_signout_btn&#039;]&#039; at zone NATIVE">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing click: Element was not identified: '//*[@id='my_account_signout_btn']' at zone NATIVE
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.ExecutionClient.execute(ExecutionClient.java:184)
	at com.experitest.client.Client.click(Client.java:463)
	at com.seetest.framework.core.MobileObjectImpl.click(MobileObjectImpl.java:26)
	at com.seetest.apps.supervalu.pages.HomePage.SignIn(HomePage.java:95)
	at com.seetest.apps.supervalu.tests.Sanity.VerfiyHomePageUI(Sanity.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- VerfiyHomePageUI -->
  <testcase name="VerfiyHomePageUI" time="80.637" classname="com.seetest.apps.supervalu.tests.Sanity"/>
</testsuite> <!-- com.seetest.apps.supervalu.tests.Sanity -->
